"use client";

import { useEffect, useState } from "react";
import AdvancedLab from "./AdvancedLab";
import LearnExperience from "./LearnExperience";

type View = "home" | "path" | "lesson" | "lab";
export type Lesson = { id:number; title:string; subtitle:string; concept:string; term:string; meaning:string; question:string; options:string[]; answer:string; fault:string; current:string; reflection:string; reflectionOptions:string[] };

const lessons:Lesson[]=[
  {id:1,title:"How power reaches people",subtitle:"Start here",concept:"Electricity travels from a source, along a power line, to places that need it.",term:"Feeder",meaning:"A power line that carries electricity from a substation to customers.",question:"What is the feeder doing?",options:["Carrying electricity to the hospital","Detecting a fault","Opening the circuit"],answer:"Carrying electricity to the hospital",fault:"Normal operation",current:"120 A",reflection:"Why do communities need several feeders?",reflectionOptions:["So one problem does not switch off every area","To make every outage larger","Because feeders detect faults"]},
  {id:2,title:"What is a fault?",subtitle:"The first danger",concept:"A fault is an unintended electrical path. It can make current rise to a dangerous level almost instantly.",term:"Fault",meaning:"An abnormal electrical condition that can damage equipment or endanger people.",question:"What is the clearest sign of this short circuit?",options:["Current rises suddenly","The hospital uses less power","Every breaker disappears"],answer:"Current rises suddenly",fault:"Three-phase short circuit",current:"4,820 A",reflection:"Why must a severe short circuit be removed quickly?",reflectionOptions:["To limit damage and danger","To increase the current","To disconnect healthy areas"]},
  {id:3,title:"Meet the relay",subtitle:"The grid notices danger",concept:"A relay watches electrical measurements. When it recognizes danger, it sends a command—it does not interrupt the current itself.",term:"Protection relay",meaning:"A monitoring device that detects abnormal conditions and decides when to trip.",question:"What should the relay do after confirming the fault?",options:["Tell the breaker to open","Carry electricity to customers","Repair the damaged cable"],answer:"Tell the breaker to open",fault:"Line-to-ground fault",current:"2,140 A",reflection:"Why does a relay wait briefly before some trips?",reflectionOptions:["To confirm the condition and avoid unnecessary trips","To make faults stronger","Because it cannot measure current"]},
  {id:4,title:"Meet the breaker",subtitle:"The grid stops danger",concept:"A circuit breaker is a powerful safety switch. It opens its contacts to stop dangerous current after receiving a trip command.",term:"Circuit breaker",meaning:"A switch designed to safely interrupt normal or fault current.",question:"Which device physically stops the fault current?",options:["Circuit breaker","Protection relay","Hospital"],answer:"Circuit breaker",fault:"Feeder fault",current:"4,820 A",reflection:"Why should the breaker nearest the fault open first?",reflectionOptions:["To isolate the smallest possible area","To switch off every customer","To remove backup protection"]},
  {id:5,title:"Keep the hospital powered",subtitle:"Protection challenge",concept:"Good protection is selective: it removes the damaged section while healthy parts of the grid continue working.",term:"Selectivity",meaning:"Disconnecting only the smallest necessary part of the power system.",question:"A fault occurs on the residential feeder. Which breaker should open?",options:["Residential feeder breaker","Main substation breaker","Hospital feeder breaker"],answer:"Residential feeder breaker",fault:"Residential earth fault",current:"2,140 A",reflection:"Why is opening the main breaker a poor result?",reflectionOptions:["The healthy hospital would also lose power","It would improve selectivity","It would repair the cable"]},
  {id:6,title:"Fault or overload?",subtitle:"Think before you trip",concept:"Not every high current is a short circuit. Motors and heavy demand can briefly increase current, so protection considers both current and time.",term:"Overload",meaning:"Current above the normal rating caused by excessive demand rather than a direct short circuit.",question:"A motor-starting current falls back quickly. What should protection do?",options:["Allow the temporary surge","Trip the entire substation instantly","Disable the relay"],answer:"Allow the temporary surge",fault:"Heavy overload",current:"780 A",reflection:"What makes overload protection different from short-circuit protection?",reflectionOptions:["It uses current and duration together","It never monitors current","It always opens every breaker"]},
];

export default function GameApp(){
  const [view,setView]=useState<View>("home");const [completed,setCompleted]=useState<number[]>([]);const [active,setActive]=useState(lessons[0]);
  useEffect(()=>{const raw=localStorage.getItem("gridlab-simple-progress");if(raw)setCompleted(JSON.parse(raw))},[]);
  function openLesson(lesson:Lesson){setActive(lesson);setView("lesson");window.scrollTo(0,0)}
  function finish(){if(!completed.includes(active.id)){const next=[...completed,active.id];setCompleted(next);localStorage.setItem("gridlab-simple-progress",JSON.stringify(next))}}
  const next=lessons.find(x=>!completed.includes(x.id))||lessons[lessons.length-1];
  return <main className="simple-app"><header className="simple-header"><button onClick={()=>setView("home")}><b>G</b><strong>GridLab</strong></button><nav><button className={view==="path"||view==="lesson"?"active":""} onClick={()=>setView("path")}>Learn</button><button className={view==="lab"?"active":""} onClick={()=>setView("lab")}>Advanced Lab</button></nav><span>{completed.length} of {lessons.length} lessons</span></header>{view==="home"?<SimpleHome start={()=>openLesson(next)} explore={()=>setView("path")} returning={completed.length>0}/>:view==="path"?<SimplePath completed={completed} open={openLesson}/>:view==="lesson"?<SimpleLesson key={active.id} lesson={active} back={()=>setView("path")} done={finish}/>:<AdvancedLab/>}</main>
}

function SimpleHome({start,explore,returning}:{start:()=>void;explore:()=>void;returning:boolean}){return <section className="simple-home"><p className="eyebrow">NO PREVIOUS POWER-SYSTEM KNOWLEDGE NEEDED</p><h1>Learn how the grid<br/>protects people.</h1><p>Follow electricity from the grid to a hospital. Then discover how relays and breakers keep dangerous faults from becoming widespread outages.</p><button className="primary" onClick={start}>{returning?"Continue learning":"Begin first lesson"} <span>→</span></button><button className="quiet-link" onClick={explore}>See the learning path</button><div className="simple-promise"><span>About 5 minutes per lesson</span><span>Learn by predicting</span><span>Interactive and self-paced</span></div><div className="one-line-grid"><div><b>~</b><span>Grid<small>Produces electricity</small></span></div><i/><div><b>/</b><span>Breaker<small>Controls the circuit</small></span></div><i/><div><b>H</b><span>Hospital<small>Needs reliable power</small></span></div></div></section>}

function SimplePath({completed,open}:{completed:number[];open:(l:Lesson)=>void}){return <section className="simple-path"><div className="simple-path-head"><p className="eyebrow">YOUR LEARNING PATH</p><h1>One idea at a time.</h1><p>Start with how electricity reaches people. Each short lesson unlocks the next.</p><div><i><b style={{width:`${completed.length/lessons.length*100}%`}}/></i><span>{completed.length} of {lessons.length} complete</span></div></div><div className="vertical-path">{lessons.map((lesson,index)=>{const unlocked=index===0||completed.includes(lesson.id-1);const done=completed.includes(lesson.id);return <div className={`${done?"done":""} ${unlocked?"":"locked"}`} key={lesson.id}><span>{done?"✓":lesson.id}</span><i/><button disabled={!unlocked} onClick={()=>open(lesson)}><small>{lesson.subtitle}</small><strong>{lesson.title}</strong><p>{unlocked?done?"Review lesson":"Start lesson":"Complete the previous lesson first"}</p></button></div>})}</div><button className="lab-after-path" onClick={()=>{}}>Advanced Lab becomes most useful after the foundations.</button></section>}

function SimpleLesson(props:{lesson:Lesson;back:()=>void;done:()=>void}){return <LearnExperience {...props}/>}

function QuietSimulation({lesson,tick}:{lesson:Lesson;tick:number}){const events=["Electricity is flowing normally",`${lesson.fault} begins`,`Current changes to ${lesson.current}`,"The relay recognizes danger","The breaker opens","The dangerous current stops"];return <div className={`quiet-sim quiet-tick-${tick}`}><header><span>WATCH THE GRID</span><strong>{events[tick]}</strong><b>{["—","0 ms","12 ms","112 ms","142 ms","144 ms"][tick]}</b></header><div className="quiet-diagram"><div><b>~</b><span>Grid</span></div><i/><div className={tick>=3?"awake":""}><b>R</b><span>Relay<small>{tick>=3?"Danger detected":"Watching"}</small></span></div><i/><div className={tick>=4?"open":""}><b><i/></b><span>Breaker<small>{tick>=4?"Open":"Closed"}</small></span></div><i/><div className={tick>0&&tick<5?"danger":""}><b>H</b><span>{lesson.id===5?"Residential area":"People"}<small>{tick>=5?"Safe":tick>0?"Fault present":"Powered"}</small></span></div></div><footer>{events.map((x,i)=><button key={x} className={tick===i?"current":tick>i?"passed":""}><span>{i+1}</span>{x}</button>)}</footer></div>}
