"use client";

import { useEffect, useState } from "react";
import AdvancedLab from "./AdvancedLab";
import LearnExperience from "./LearnExperience";

type View = "home" | "path" | "mission" | "lab";
export type Mission = {
  id:number; title:string; chapter:string; rank:string; story:string; evidence:string;
  concept:string; term:string; meaning:string; question:string; options:string[];
  answer:string; fault:string; current:string; normalCurrent:string; multiplier:string;
  reflection:string; reflectionOptions:string[];
};

const missions:Mission[]=[
  {id:1,title:"Power reaches the hospital",chapter:"Substation fundamentals",rank:"Grid Explorer",story:"It is 7:00 a.m. The hospital is opening its theatres. Trace the path that keeps its equipment alive.",evidence:"The feeder carries 120 A. Every breaker is closed.",concept:"Electricity travels from a source, along a feeder, to places that need it.",term:"Feeder",meaning:"A power line that carries electricity from a substation to customers.",question:"What is the feeder doing?",options:["Carrying electricity to the hospital","Detecting a fault","Opening the circuit"],answer:"Carrying electricity to the hospital",fault:"Normal operation",current:"120 A",normalCurrent:"120 A",multiplier:"Normal",reflection:"Why do communities need several feeders?",reflectionOptions:["So one problem does not switch off every area","To make every outage larger","Because feeders detect faults"]},
  {id:2,title:"The first fault",chapter:"Fault investigation",rank:"Fault Investigator",story:"A loud flash is reported near a community feeder. The control room sees only one clue: current has surged.",evidence:"Current jumped from 120 A to 4,820 A in an instant.",concept:"A fault creates an unintended electrical path and can raise current to a dangerous level almost instantly.",term:"Fault",meaning:"An abnormal electrical condition that can damage equipment or endanger people.",question:"What is the strongest evidence of a short circuit?",options:["Current rises suddenly","The hospital uses less power","Every breaker disappears"],answer:"Current rises suddenly",fault:"Three-phase short circuit",current:"4,820 A",normalCurrent:"120 A",multiplier:"40× normal",reflection:"Why must a severe short circuit be removed quickly?",reflectionOptions:["To limit damage and danger","To increase the current","To disconnect healthy areas"]},
  {id:3,title:"Meet your relay",chapter:"Relay detection",rank:"Relay Observer",story:"The fault is still energized. A protection relay has milliseconds to decide whether the signal is dangerous.",evidence:"The relay measures 2,140 A and detects current returning through earth.",concept:"A relay watches electrical measurements and sends a command when it recognizes danger. It does not interrupt current itself.",term:"Protection relay",meaning:"A monitoring device that detects abnormal conditions and decides when to trip.",question:"What should the relay do after confirming the fault?",options:["Tell the breaker to open","Carry electricity to customers","Repair the damaged cable"],answer:"Tell the breaker to open",fault:"Line-to-ground fault",current:"2,140 A",normalCurrent:"120 A",multiplier:"18× normal",reflection:"Why does a relay wait briefly before some trips?",reflectionOptions:["To confirm the condition and avoid unnecessary trips","To make faults stronger","Because it cannot measure current"]},
  {id:4,title:"The breaker's decision",chapter:"Breaker operation",rank:"Breaker Operator",story:"The relay has issued a trip command. Dangerous current is still flowing toward the community.",evidence:"A confirmed feeder fault is carrying 4,820 A.",concept:"A circuit breaker is a powerful safety switch. It opens its contacts to stop dangerous current after a trip command.",term:"Circuit breaker",meaning:"A switch designed to safely interrupt normal or fault current.",question:"Which device physically stops the fault current?",options:["Circuit breaker","Protection relay","Hospital"],answer:"Circuit breaker",fault:"Feeder fault",current:"4,820 A",normalCurrent:"120 A",multiplier:"40× normal",reflection:"Why should the breaker nearest the fault open first?",reflectionOptions:["To isolate the smallest possible area","To switch off every customer","To remove backup protection"]},
  {id:5,title:"Protect the hospital",chapter:"Protection coordination",rank:"Selective Protector",story:"A residential cable faults beside a hospital feeder. One wrong breaker choice could darken an operating theatre.",evidence:"Residential earth current is 2,140 A. The hospital feeder remains healthy.",concept:"Good protection is selective: it removes the damaged section while healthy parts of the grid continue working.",term:"Selectivity",meaning:"Disconnecting only the smallest necessary part of the power system.",question:"You only know the residential feeder is faulted. Which breaker should open?",options:["Residential feeder breaker","Main substation breaker","Hospital feeder breaker"],answer:"Residential feeder breaker",fault:"Residential earth fault",current:"2,140 A",normalCurrent:"120 A",multiplier:"18× normal",reflection:"Why is opening the main breaker a poor result?",reflectionOptions:["The healthy hospital would also lose power","It would improve selectivity","It would repair the cable"]},
  {id:6,title:"Fault or overload?",chapter:"Engineering judgement",rank:"Protection Engineer",story:"The factory starts every motor at once. Current climbs sharply—but tripping too soon could stop production for no reason.",evidence:"Current rises to 780 A, then begins falling without fault indicators.",concept:"Not every high current is a short circuit. Protection considers both current and time before acting.",term:"Overload",meaning:"Current above normal rating caused by excessive demand rather than a direct short circuit.",question:"Motor-starting current falls back quickly. What should protection do?",options:["Allow the temporary surge","Trip the entire substation instantly","Disable the relay"],answer:"Allow the temporary surge",fault:"Heavy overload",current:"780 A",normalCurrent:"120 A",multiplier:"6.5× normal",reflection:"What makes overload protection different from short-circuit protection?",reflectionOptions:["It uses current and duration together","It never monitors current","It always opens every breaker"]},
];

export default function GameApp(){
  const [view,setView]=useState<View>("home"); const [completed,setCompleted]=useState<number[]>([]); const [active,setActive]=useState(missions[0]);
  useEffect(()=>{const raw=localStorage.getItem("gridlab-simple-progress");if(raw)setCompleted(JSON.parse(raw))},[]);
  function openMission(mission:Mission){setActive(mission);setView("mission");window.scrollTo(0,0)}
  function finish(){if(!completed.includes(active.id)){const next=[...completed,active.id];setCompleted(next);localStorage.setItem("gridlab-simple-progress",JSON.stringify(next))}}
  const next=missions.find(x=>!completed.includes(x.id))||missions[missions.length-1];
  return <main className="simple-app"><header className="simple-header"><button onClick={()=>setView("home")} aria-label="GridLab home"><b>G</b><strong>GridLab</strong></button><nav aria-label="Primary navigation"><button className={view==="path"||view==="mission"?"active":""} onClick={()=>setView("path")}>Missions</button><button className={view==="lab"?"active":""} onClick={()=>setView("lab")}>Advanced Lab</button></nav><span>{completed.length} of {missions.length} missions</span></header>{view==="home"?<Home start={()=>openMission(next)} explore={()=>setView("path")} returning={completed.length>0}/>:view==="path"?<ProgressMap completed={completed} open={openMission}/>:view==="mission"?<LearnExperience key={active.id} mission={active} back={()=>setView("path")} done={finish}/>:<AdvancedLab/>}</main>
}

function Home({start,explore,returning}:{start:()=>void;explore:()=>void;returning:boolean}){return <section className="simple-home"><p className="eyebrow">INTERACTIVE PROTECTION LEARNING LABORATORY</p><h1>Learn to think like a<br/>protection engineer.</h1><p className="hero-line">Predict faults. Observe relays. Protect communities.</p><p>No previous power-system knowledge needed. Begin with one hospital feeder and build the judgement to coordinate an entire substation.</p><button className="primary" onClick={start}>{returning?"Continue your mission":"Begin Mission 1"} <span>→</span></button><button className="quiet-link" onClick={explore}>View your progression map</button><div className="simple-promise"><span>Story-driven missions</span><span>Predict before reveal</span><span>About 5 minutes each</span></div><div className="one-line-grid" aria-label="Electricity travels from the grid through protection to a hospital"><div><b>~</b><span>Grid<small>Supplies electricity</small></span></div><i/><div><b>R</b><span>Relay<small>Detects danger</small></span></div><i/><div><b>/</b><span>Breaker<small>Stops fault current</small></span></div><i/><div><b>H</b><span>Hospital<small>Must stay powered</small></span></div></div></section>}

function ProgressMap({completed,open}:{completed:number[];open:(m:Mission)=>void}){return <section className="simple-path"><div className="simple-path-head"><p className="eyebrow">PROTECTION ENGINEER PROGRESSION MAP</p><h1>Your route to the control room.</h1><p>Every mission adds one decision to your engineering toolkit.</p><div><i><b style={{width:`${completed.length/missions.length*100}%`}}/></i><span>{completed.length} of {missions.length} complete</span></div></div><div className="vertical-path">{missions.map((mission,index)=>{const unlocked=index===0||completed.includes(mission.id-1);const done=completed.includes(mission.id);return <div className={`${done?"done":""} ${unlocked?"":"locked"}`} key={mission.id}><span>{done?"✓":mission.id}</span><i/><button disabled={!unlocked} onClick={()=>open(mission)}><small>{mission.chapter}</small><strong>Mission {mission.id} · {mission.title}</strong><p>{unlocked?done?`Review · ${mission.rank}`:`Next rank: ${mission.rank}`:"Complete the previous mission to unlock"}</p></button></div>})}</div><button className="lab-after-path" onClick={()=>{}}>Advanced Lab · open experimentation after the foundations</button></section>}
