"use client";

import { useEffect, useState } from "react";
import type { Lesson } from "./GameApp";
import PowerSystemSimulation from "./PowerSystemSimulation";

export default function LearnExperience({lesson,back,done}:{lesson:Lesson;back:()=>void;done:()=>void}){
  const [stage,setStage]=useState<"learn"|"predict"|"watch"|"understand">("learn");
  const [choice,setChoice]=useState<string|null>(null); const [tick,setTick]=useState(0); const [playing,setPlaying]=useState(false); const [reflection,setReflection]=useState<string|null>(null);
  const correct=choice===lesson.answer;
  useEffect(()=>{if(stage!=="watch"||!playing||tick>=5){if(tick>=5)setPlaying(false);return}const timer=setTimeout(()=>setTick(value=>value+1),1100);return()=>clearTimeout(timer)},[playing,stage,tick]);
  function begin(){setTick(0);setPlaying(true);setStage("watch")}
  return <section className="simple-lesson"><div className="lesson-top"><button onClick={back}>← Learning path</button><div>{["Learn","Predict","Simulate","Understand"].map((x,i)=><span className={i<=["learn","predict","watch","understand"].indexOf(stage)?"active":""} key={x}>{i+1}<small>{x}</small></span>)}</div><b>LESSON {lesson.id}</b></div>
    {stage==="learn"&&<div className="focus-card learn-focus"><p className="eyebrow">ONE NEW IDEA</p><h1>{lesson.title}</h1><p>{lesson.concept}</p><div className="concept-preview"><div><b>~</b><span>Electricity</span></div><i/><div><b>{lesson.id<3?"?":"R"}</b><span>{lesson.id<3?"Something changes":lesson.term}</span></div><i/><div><b>H</b><span>People need power</span></div></div><div className="new-word"><span>NEW WORD</span><strong>{lesson.term}</strong><p>{lesson.meaning}</p></div><button className="primary" onClick={()=>setStage("predict")}>Try a prediction <span>→</span></button></div>}
    {stage==="predict"&&<div className="focus-card predict-focus"><p className="eyebrow">MAKE A PREDICTION</p><h2>{lesson.question}</h2><div>{lesson.options.map((x,i)=><button className={choice===x?"selected":""} onClick={()=>setChoice(x)} key={x}><span>{String.fromCharCode(65+i)}</span>{x}</button>)}</div><button disabled={!choice} className="primary" onClick={begin}>Run the simulation <span>→</span></button></div>}
    {stage==="watch"&&<PowerSystemSimulation lesson={lesson} tick={tick} playing={playing} setTick={setTick} setPlaying={setPlaying} explain={()=>setStage("understand")}/>}
    {stage==="understand"&&<div className="understand-screen"><div className="understand-result"><span>{correct?"YOUR PREDICTION WAS CORRECT":"LET'S CORRECT THE IDEA"}</span><h1>{correct?"You understood the system response.":`The best response was: ${lesson.answer}.`}</h1><p>{lesson.concept}</p><div><p><span>CURRENT</span><strong>{lesson.current}</strong></p><p><span>CLEARING</span><strong>{lesson.id===1||lesson.id===6?"No trip":"144 ms"}</strong></p><p><span>HEALTHY POWER</span><strong>Preserved</strong></p></div></div><div className="one-reflection"><span>ENGINEERING REFLECTION</span><h2>{lesson.reflection}</h2>{lesson.reflectionOptions.map((x,i)=><button key={x} className={reflection===x?(i===0?"correct":"wrong"):""} onClick={()=>setReflection(x)}><i>{String.fromCharCode(65+i)}</i>{x}</button>)}{reflection&&<p><b>{reflection===lesson.reflectionOptions[0]?"Correct.":"Not quite."}</b> {reflection===lesson.reflectionOptions[0]?"That is the key engineering principle.":"Review what changed and which areas should remain powered."}</p>}<button disabled={!reflection} className="primary" onClick={()=>{done();back()}}>Finish lesson <span>→</span></button></div></div>}
  </section>
}

function RichLearnSimulation({lesson,tick,playing,setTick,setPlaying,explain}:{lesson:Lesson;tick:number;playing:boolean;setTick:(n:number)=>void;setPlaying:(p:boolean)=>void;explain:()=>void}){
  const overload=lesson.id===6, normal=lesson.id===1, selectivity=lesson.id===5;
  const events=normal?["Source supplies power","Current enters the feeder","Power passes the closed breaker","Electricity reaches the hospital","The hospital remains powered","Normal operation continues"]:overload?["Factory demand increases","Current rises gradually","Relay starts an overload timer","The current begins falling","Breaker correctly remains closed","Normal supply continues"]:["System is operating normally",`${lesson.fault} begins`,`Current rises to ${lesson.current}`,"Relay detects the abnormal current","Breaker opens its contacts","Fault is isolated safely"];
  const current=normal?["0 A","40 A","85 A","120 A","120 A","120 A"][tick]:overload?["120 A","430 A","780 A","610 A","410 A","410 A"][tick]:["120 A",lesson.current,lesson.current,lesson.current,"0 A","0 A"][tick];
  const tripped=!normal&&!overload&&tick>=4;
  return <div className={`rich-learn-sim scenario-${lesson.id} tick-${tick}`}><header><div><span>{playing?"● SIMULATION RUNNING":tick===5?"SIMULATION COMPLETE":"SIMULATION PAUSED"}</span><strong>{events[tick]}</strong></div><div><span>LIVE CURRENT</span><b>{current}</b></div></header><div className="rich-scene"><div className="scene-help">{tick===0?"Follow the black pulses. They represent electricity moving through the system.":events[tick]}</div><div className="rich-source"><b>~</b><span>Power source<small>11,000 volts</small></span></div><div className={`rich-wire wire-in ${tripped?"dead":""}`}><i/><i/><i/></div><div className={`rich-relay ${tick>=3&&!normal&&!overload&&tick<5?"detecting":""}`}><b>R</b><span>Protection relay<small>{tick>=3?overload?"Timing overload":"Danger detected":"Watching current"}</small></span></div><div className={`rich-breaker ${tripped?"open":""}`}><b><i/></b><span>Circuit breaker<small>{tripped?"OPEN":"CLOSED"}</small></span></div><div className={`rich-wire wire-out ${tripped?"dead":""}`}><i/><i/><i/></div>{selectivity?<div className="rich-branches"><div className={tripped?"off":"fault-zone"}><b>R</b><span>Residential<small>{tripped?"Power isolated":"Faulted"}</small></span></div><div><b>H</b><span>Hospital<small>Still powered</small></span></div></div>:<div className={`rich-load ${tick>0&&!normal&&!overload&&tick<5?"faulting":""} ${overload&&tick>0&&tick<4?"overloaded":""}`}><b>{lesson.id===6?"F":"H"}</b><span>{lesson.id===6?"Factory":"Community"}<small>{tripped?"Safely isolated":overload?"Motor demand":"Powered"}</small></span></div>}<div className="current-gauge"><span>CURRENT LEVEL</span><div><i style={{width:`${normal?Math.min(100,tick*20):overload?[12,45,82,64,43,43][tick]:tick===0?12:tick>=4?0:95}%`}}/></div><b>{current}</b></div></div><div className="rich-event-strip">{events.map((event,index)=><button key={event} onClick={()=>{setTick(index);setPlaying(false)}} className={tick===index?"current":tick>index?"passed":""}><span>{index+1}</span><p>{event}</p></button>)}</div><div className="sim-controls"><button className="secondary" disabled={tick===0} onClick={()=>{setTick(Math.max(0,tick-1));setPlaying(false)}}>← Previous</button><button className="secondary" onClick={()=>setPlaying(!playing)}>{playing?"Pause":"Auto play"}</button>{tick<5?<button className="primary" onClick={()=>{setTick(Math.min(5,tick+1));setPlaying(false)}}>Next event <span>→</span></button>:<button className="primary" onClick={explain}>Explain the result <span>→</span></button>}</div></div>
}
