"use client";

import { useEffect, useState } from "react";
import type { Mission } from "./GameApp";
import PowerSystemSimulation from "./PowerSystemSimulation";

export default function LearnExperience({mission,back,done}:{mission:Mission;back:()=>void;done:()=>void}){
  const [stage,setStage]=useState<"brief"|"investigate"|"watch"|"debrief">("brief");
  const [choice,setChoice]=useState<string|null>(null); const [tick,setTick]=useState(0); const [playing,setPlaying]=useState(false); const [reflection,setReflection]=useState<string|null>(null);
  const predictionCorrect=choice===mission.answer; const reflectionCorrect=reflection===mission.reflectionOptions[0];
  const score=(predictionCorrect?1:0)+(reflectionCorrect?1:0)+1;
  useEffect(()=>{if(stage!=="watch"||!playing||tick>=5){if(tick>=5)setPlaying(false);return}const timer=setTimeout(()=>setTick(value=>value+1),1100);return()=>clearTimeout(timer)},[playing,stage,tick]);
  function begin(){setTick(0);setPlaying(true);setStage("watch")}
  return <section className="simple-lesson"><div className="lesson-top"><button onClick={back}>← All missions</button><div>{["Situation","Decide","Watch","Result"].map((x,i)=><span className={i<=["brief","investigate","watch","debrief"].indexOf(stage)?"active":""} key={x}>{i+1}<small>{x}</small></span>)}</div><b>MISSION {mission.id}</b></div>
    {stage==="brief"&&<div className="focus-card mission-brief"><div className="mission-brief-head"><p className="eyebrow">MISSION {String(mission.id).padStart(2,"0")} · YOUR SITUATION</p><h1>{mission.title}</h1><p>{mission.story}</p></div><div className="mission-brief-info"><div><span>YOUR CLUE</span><strong>{mission.evidence}</strong></div><div><span>{mission.term}</span><p>{mission.meaning}</p></div></div><button className="primary" onClick={()=>setStage("investigate")}>Make your decision <span>→</span></button></div>}
    {stage==="investigate"&&<div className="focus-card predict-focus"><p className="eyebrow">WHAT SHOULD HAPPEN?</p><h2>{mission.question}</h2><div className="evidence-only"><span>YOUR CLUE</span><strong>{mission.evidence}</strong><small>Choose your best answer. The circuit will show what your decision causes.</small></div><div>{mission.options.map((x,i)=><button className={choice===x?"selected":""} onClick={()=>setChoice(x)} key={x}><span>{String.fromCharCode(65+i)}</span>{x}</button>)}</div><button disabled={!choice} className="primary" onClick={begin}>Run my decision <span>→</span></button></div>}
    {stage==="watch"&&<PowerSystemSimulation lesson={mission} prediction={choice||""} tick={tick} playing={playing} setTick={setTick} setPlaying={setPlaying} explain={()=>setStage("debrief")}/>}
    {stage==="debrief"&&<div className="understand-screen"><div className="understand-result"><span>WHAT HAPPENED</span><h1>{predictionCorrect?"Good call—the system stayed protected.":"That decision caused a protection problem."}</h1><div className="prediction-compare"><p><span>YOU CHOSE</span><strong>{choice}</strong></p><p><span>BEST RESPONSE</span><strong>{mission.answer}</strong></p></div><p>{predictionCorrect?mission.concept:mission.id===5&&choice?.includes("Hospital")?"The hospital lost power, but the residential fault remained energized. Protection must remove the faulted section—not a healthy critical load.":mission.concept}</p><div className="energy-story"><p><span>CURRENT</span><strong>{mission.current}</strong><small>{mission.multiplier} · normal is {mission.normalCurrent}</small></p><p><span>FAULT CLEARED</span><strong>{predictionCorrect&&mission.id!==1&&mission.id!==6?"144 ms":mission.id===1||mission.id===6?"No trip needed":"Not cleared"}</strong></p><p><span>IMPACT</span><strong>{predictionCorrect?"Contained":"Review needed"}</strong></p></div></div><div className="one-reflection"><span>ONE LAST QUESTION</span><h2>{mission.reflection}</h2>{mission.reflectionOptions.map((x,i)=><button key={x} className={reflection===x?(i===0?"correct":"wrong"):""} onClick={()=>setReflection(x)}><i>{String.fromCharCode(65+i)}</i>{x}</button>)}{reflection&&<><div className="understanding-score"><span>YOUR UNDERSTANDING</span><strong>{score} of 3</strong><i><b style={{width:`${score/3*100}%`}}/></i><small>{predictionCorrect?"Decision: correct":"Decision: revise"} · {reflectionCorrect?"Reason: correct":"Reason: revise"} · Impact: observed</small></div><p><b>{reflectionCorrect?"Exactly.":"Try that idea again."}</b> {reflectionCorrect?"You connected the system response to the protection principle.":"Think about what changed, what stayed healthy, and which device should act first."}</p></>}<button disabled={!reflection} className="primary" onClick={()=>{done();back()}}>Finish mission <span>→</span></button></div></div>}
  </section>
}
