"use client";

import { useEffect, useState } from "react";
import type { Mission } from "./GameApp";
import PowerSystemSimulation from "./PowerSystemSimulation";

export default function LearnExperience({mission,back,done}:{mission:Mission;back:()=>void;done:()=>void}){
  const [stage,setStage]=useState<"brief"|"investigate"|"watch"|"debrief">("brief");
  const [choice,setChoice]=useState<string|null>(null); const [tick,setTick]=useState(0); const [playing,setPlaying]=useState(false); const [reflection,setReflection]=useState<string|null>(null);
  const predictionCorrect=choice===mission.answer; const reflectionCorrect=reflection===mission.reflectionOptions[0];
  const score=(predictionCorrect?1:0)+(reflectionCorrect?1:0)+1;
  useEffect(()=>{if(stage!=="watch"||!playing||tick>=5){if(tick>=5)setPlaying(false);return}const timer=setTimeout(()=>setTick(value=>value+1),1100);return()=>clearTimeout(timer)},[playing,stage,tick]);
  function begin(){setTick(0);setPlaying(true);setStage("watch")}
  return <section className="simple-lesson"><div className="lesson-top"><button onClick={back}>← Progress map</button><div>{["Brief","Investigate","Simulate","Debrief"].map((x,i)=><span className={i<=["brief","investigate","watch","debrief"].indexOf(stage)?"active":""} key={x}>{i+1}<small>{x}</small></span>)}</div><b>MISSION {mission.id}</b></div>
    {stage==="brief"&&<div className="focus-card mission-brief"><p className="eyebrow">CONTROL ROOM BRIEF</p><span className="mission-number">MISSION {String(mission.id).padStart(2,"0")}</span><h1>{mission.title}</h1><blockquote>{mission.story}</blockquote><div className="brief-signal"><span>INCOMING FIELD REPORT</span><strong>{mission.evidence}</strong></div><div className="new-word"><span>ENGINEERING TOOLKIT · NEW TERM</span><strong>{mission.term}</strong><p>{mission.meaning}</p></div><button className="primary" onClick={()=>setStage("investigate")}>Inspect the evidence <span>→</span></button></div>}
    {stage==="investigate"&&<div className="focus-card predict-focus"><p className="eyebrow">PROTECTION COACH · MAKE THE CALL</p><h2>{mission.question}</h2><div className="evidence-only"><span>AVAILABLE EVIDENCE</span><strong>{mission.evidence}</strong><small>No equipment labels or solution hints will be revealed until you commit.</small></div><div>{mission.options.map((x,i)=><button className={choice===x?"selected":""} onClick={()=>setChoice(x)} key={x}><span>{String.fromCharCode(65+i)}</span>{x}</button>)}</div><button disabled={!choice} className="primary" onClick={begin}>Lock decision and simulate <span>→</span></button></div>}
    {stage==="watch"&&<PowerSystemSimulation lesson={mission} prediction={choice||""} tick={tick} playing={playing} setTick={setTick} setPlaying={setPlaying} explain={()=>setStage("debrief")}/>}
    {stage==="debrief"&&<div className="understand-screen"><div className="understand-result"><span>MISSION DEBRIEF</span><h1>{predictionCorrect?"Your protection decision held.":"The system exposed a weakness."}</h1><div className="prediction-compare"><p><span>YOUR DECISION</span><strong>{choice}</strong></p><p><span>ENGINEER'S RESPONSE</span><strong>{mission.answer}</strong></p></div><p>{predictionCorrect?mission.concept:mission.id===5&&choice?.includes("Hospital")?"The hospital lost power, but the residential fault remained energized. Protection must remove the faulted section—not a healthy critical load.":mission.concept}</p><div className="energy-story"><p><span>ENERGY STORY</span><strong>{mission.current}</strong><small>{mission.multiplier} · baseline {mission.normalCurrent}</small></p><p><span>CLEARING</span><strong>{predictionCorrect&&mission.id!==1&&mission.id!==6?"144 ms":mission.id===1||mission.id===6?"No trip":"Not cleared"}</strong></p><p><span>COMMUNITY IMPACT</span><strong>{predictionCorrect?"Contained":"Review required"}</strong></p></div></div><div className="one-reflection"><span>ENGINEERING REFLECTION</span><h2>{mission.reflection}</h2>{mission.reflectionOptions.map((x,i)=><button key={x} className={reflection===x?(i===0?"correct":"wrong"):""} onClick={()=>setReflection(x)}><i>{String.fromCharCode(65+i)}</i>{x}</button>)}{reflection&&<><div className="understanding-score"><span>MISSION UNDERSTANDING</span><strong>{score} of 3</strong><i><b style={{width:`${score/3*100}%`}}/></i><small>{predictionCorrect?"Breaker decision: correct":"Breaker decision: revise"} · {reflectionCorrect?"Reasoning: correct":"Reasoning: revise"} · Impact: observed</small></div><p><b>{reflectionCorrect?"Strong reasoning.":"Not quite."}</b> {reflectionCorrect?"You connected the system response to the engineering principle.":"Review what changed, what stayed healthy, and which device should act first."}</p></>}<button disabled={!reflection} className="primary" onClick={()=>{done();back()}}>Complete mission <span>→</span></button></div></div>}
  </section>
}
